### ISSUE TITLE
Error creating playlist first: Read-only file system

### ISSUE THREAD

**Issue by stef97** [bestlibre/hassio-addons#129]
I am trying to use iris to create play lists but I am getting the above error 
Is it possible to do that or should I upload playlist in the share/mopidy/playlsist directory ?

I 've aleady changed permissions on mopidy `directory` 

`/home/user/docker/hassio/homeassistant# ls -la ../share/mopidy/
total 16
drwxrwxrwx 4 root root 4096 Nov 21 15:06 .
drwxr-xr-x 5 root root 4096 Nov 21 15:05 ..
drwxrwxrwx 2 root root 4096 Nov 21 15:43 media
drwxrwxrwx 2 root root 4096 Nov 21 15:06 playlists
`

**Comment by miqmago** [comment]
It seems that the container has no permissions on the volume. I've tried to change the local dir via this configuration and result is the same:

```yml
local_scan: true
options:
  - name: local/media_dir
    value: /data/mopidy/media
```
